hugo:
  image: jojomi/hugo:latest
  volumes:
    - ./src/:/src
    - ./docs/:/output
  environment:
    - HUGO_REFRESH_TIME=3600
    - HUGO_WATCH=yes
    - HUGO_THEME=minimo
    - HUGO_BASEURL=ddffx.github.io/blockchain-blog
  restart: always
  ports:
    - "1313:1313"
  container_name: blockchain-blog